export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const SAVE_ORDERS = 'SAVE_ORDERS';
export const CLEAR_CART = 'CLEAR_CART';
