/* eslint-disable react-native/no-inline-styles */
import React from 'react'
import { ScrollView, View ,Image, Text} from 'react-native'
import { Header, Iconlabel, LineDivider, Ratings, StepperIncrement, TextButton, TextIconButton } from '../../Components'
import { COLORS ,SIZES,icons, FONTS,images, dummyData} from '../../constants'
const FoodDetails = ({navigation}) => {
  return (
    <View
    style={{
        flex:1,
        backgroundColor:COLORS.white
    }}
    >
    <Header
    containerStye={{
            height:50,
            marginTop:10,
            alignItems:'center',
            paddingHorizontal:SIZES.padding
    }}
        title="Mangos"
        leftComponent={
            <TextIconButton
            iconLeft={icons.back}
            containerStyle={{
                width:40,
                height:40,
                justifyContent:'center',
                alignItems:'center',
                borderWidth:1,
                borderRadius:SIZES.radius,
                borderColor:COLORS.gray2
            }}
            iconStyle={{
                width:20,
                height:20,
                tintColor:COLORS.gray2,
                marginRight:SIZES.base
            }}
            onPress={()=>{
                navigation.pop()
            }}
            />
        }
    />
    <ScrollView>
        <View style={{
            marginTop:SIZES.radius,
            marginBottom:SIZES.padding,
            paddingHorizontal:SIZES.padding
        }}>
            <View style={{
                height:190,
                borderRadius:SIZES.radius,
                backgroundColor:COLORS.lightGray2
            }}>
                <View 
                style={{
                    flexDirection:'row',
                    justifyContent:'space-between',
                    marginTop:SIZES.base,
                    paddingHorizontal:SIZES.radius
                }}
                >
                    <View
                    style={{
                        flexDirection:'row'
                    }}
                    >
                        <Image
                            source={icons.calories}
                            style={{
                                width:30,
                                height:30
                            }}
                        />
                        <Text style={{
                            ...FONTS.body4,
                            color:COLORS.darkGray2
                        }}>
                            125Calories
                        </Text>
                    </View>
                    <Image
                    source={icons.love}
                    style={{
                        height:30,
                        width:30,
                        tintColor:COLORS.primary
                    }}
                    />
                </View>
                <Image
                source={dummyData.menu[0].list[0].image}
                resizeMode="contain"
                style={{
                    height:170,
                    width:'100%'
                }}
                />
            </View>
            <View
            style={{
                marginTop:SIZES.padding
            }}
            >
                <Text
                style={{
                    ...FONTS.h1
                }}
                >
                    {dummyData.menu[0].list[0].name}
                </Text>
                <Text
                style={{
                    marginTop:SIZES.base,
                    ...FONTS.body3,
                    color:COLORS.darkGray,
                    textAlign:'justify'
                }}
                >
                {dummyData.menu[0].list[0].description}
                </Text>
                <View
                style={{
                    flexDirection:'row',
                    marginTop:SIZES.padding
                }}
                >
                <Iconlabel
                containerStyle={{
                    backgroundColor:COLORS.primary,
                }}
                    icon={icons.star}
                    label="4.5"
                    labelStyle={{
                        color:COLORS.white
                    }}
                />
                <Iconlabel
                containerStyle={{
                    marginLeft:SIZES.radius,
                    paddingHorizontal:0
                    
                }}
                    icon={icons.clock}
                    label="30min"
                    labelStyle={{
                        color:COLORS.black
                    }}
                    iconStyle={{
                        tintColor:COLORS.black
                    }}
                />
                <Iconlabel
                containerStyle={{
                    marginLeft:SIZES.radius,
                    paddingHorizontal:0
                    
                }}
                    icon={icons.dollar}
                    label="Best Seller"
                    labelStyle={{
                        color:COLORS.black
                    }}
                    iconStyle={{
                        tintColor:COLORS.black
                    }}
                />
                </View>
                <View
                    style={{
                        flexDirection:'row',
                        marginTop:SIZES.padding,
                        alignItems:'center',
                    }}
                >
                    <Text
                    style={{
                        ...FONTS.h3,
                    }}
                    >
                      Sizes:
                    </Text>
                    <View
                        style={{
                            flexDirection:'row',
                            flexWrap:'wrap',
                            marginLeft:SIZES.padding
                        }}
                    >
                       <TextButton
                        label={"11\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       />
                       <TextButton
                        label={"12\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       />
                       <TextButton
                        label={"13\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       /> 
                    </View>
                </View>
            </View>
        </View>
        <LineDivider/>
        <View
            style={{
                flexDirection:'row',
                marginVertical:SIZES.padding,
                paddingHorizontal:SIZES.padding,
                alignItems:'center'
            }}
        >
            <Image
            source={images.profile}
            style={{
                width:50,
                height:50,
                borderRadius:SIZES.radius
            }}
            />
            <View
            style={{
                flex:1,
                marginLeft:SIZES.radius,
                justifyContent:'center'
            }}
            >
                <Text style={{...FONTS.h3}}>John Doe</Text>
                <Text style={{...FONTS.body4,color:COLORS.gray}}>12.5 KM away from here</Text>
                
            </View>
            <Ratings
                rating={4}
                iconStyle={{
                    marginLeft:3,
                }}
                />
        </View>
    </ScrollView>
    <LineDivider/>
    <View
    style={{
        flexDirection:'row',
        height:90,
        alignItems:'center',
        paddingHorizontal:SIZES.padding,
        paddingBottom:SIZES.radius
    }}
    ><StepperIncrement
            onAdd={()=>{}}
            onMinus={()=>{}}
            value={4}
        />
        <TextButton
        buttonContainerStyle={{
            flex:1,
            flexDirection:'row',
            height:60,
            marginLeft:SIZES.radius,
            paddingHorizontal:SIZES.radius,
            borderRadius:SIZES.radius
        }}
        label="Buy Now"
        label2='$12.99'
        
        />
    </View>
    </View>
  )
}

export default FoodDetails