/* eslint-disable react-native/no-inline-styles */
import React from 'react'
import { ScrollView, View ,Image, Text} from 'react-native'
import { Header, Iconlabel, TextButton } from '../../Components'
import { COLORS ,SIZES,icons, FONTS,images, dummyData} from '../../constants'
const FoodDetails = ({navigation}) => {
  return (
    <View
    style={{
        flex:1,
        backgroundColor:COLORS.white
    }}
    >
    <Header
    containerStye={{
            height:50,
            marginTop:10,
            alignItems:'center',
            paddingHorizontal:SIZES.padding
    }}
        title="Manof"
    />
    <ScrollView>
        <View style={{
            marginTop:SIZES.radius,
            marginBottom:SIZES.padding,
            paddingHorizontal:SIZES.padding
        }}>
            <View style={{
                height:190,
                borderRadius:SIZES.radius,
                backgroundColor:COLORS.lightGray2
            }}>
                <View 
                style={{
                    flexDirection:'row',
                    justifyContent:'space-between',
                    marginTop:SIZES.base,
                    paddingHorizontal:SIZES.radius
                }}
                >
                    <View
                    style={{
                        flexDirection:'row'
                    }}
                    >
                        <Image
                            source={icons.calories}
                            style={{
                                width:30,
                                height:30
                            }}
                        />
                        <Text style={{
                            ...FONTS.body4,
                            color:COLORS.darkGray2
                        }}>
                            125Calories
                        </Text>
                    </View>
                    <Image
                    source={icons.love}
                    style={{
                        height:30,
                        width:30,
                        tintColor:COLORS.primary
                    }}
                    />
                </View>
                <Image
                source={dummyData.menu[0].list[0].image}
                resizeMode="contain"
                style={{
                    height:170,
                    width:'100%'
                }}
                />
            </View>
            <View
            style={{
                marginTop:SIZES.padding
            }}
            >
                <Text
                style={{
                    ...FONTS.h1
                }}
                >
                    {dummyData.menu[0].list[0].name}
                </Text>
                <Text
                style={{
                    marginTop:SIZES.base,
                    ...FONTS.body3,
                    color:COLORS.darkGray,
                    textAlign:'justify'
                }}
                >
                {dummyData.menu[0].list[0].description}
                </Text>
                <View
                style={{
                    flexDirection:'row',
                    marginTop:SIZES.padding
                }}
                >
                <Iconlabel
                containerStyle={{
                    backgroundColor:COLORS.primary,
                }}
                    icon={icons.star}
                    label="4.5"
                    labelStyle={{
                        color:COLORS.white
                    }}
                />
                <Iconlabel
                containerStyle={{
                    marginLeft:SIZES.radius,
                    paddingHorizontal:0
                    
                }}
                    icon={icons.coupon}
                    label="30min"
                    labelStyle={{
                        color:COLORS.black
                    }}
                    iconStyle={{
                        tintColor:COLORS.black
                    }}
                />
                <Iconlabel
                containerStyle={{
                    marginLeft:SIZES.radius,
                    paddingHorizontal:0
                    
                }}
                    icon={icons.help}
                    label="Free Shipping"
                    labelStyle={{
                        color:COLORS.black
                    }}
                    iconStyle={{
                        tintColor:COLORS.black
                    }}
                />
                </View>
                <View
                    style={{
                        flexDirection:'row',
                        marginTop:SIZES.padding,
                        alignItems:'center',
                    }}
                >
                    <Text
                    style={{
                        ...FONTS.h3,
                    }}
                    >
                      Sizes:
                    </Text>
                    <View
                        style={{
                            flexDirection:'row',
                            flexWrap:'wrap',
                            marginLeft:SIZES.padding
                        }}
                    >
                       <TextButton
                        label={"11\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       />
                       <TextButton
                        label={"12\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       />
                       <TextButton
                        label={"13\""}
                        buttonContainerStyle={{
                            width:45,
                            height:45,
                            borderRadius:SIZES.radius,
                            borderWidth:1,
                            backgroundColor:null,
                            margin:SIZES.base,
                            borderColor:COLORS.gray
                        }}
                        labelStyle={{
                            ...FONTS.h3
                        }}
                       /> 
                    </View>
                </View>
            </View>
        </View>
    </ScrollView>
    </View>
  )
}

export default FoodDetails